# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180810_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[(b'0', b'reset_request'), (b'1', b'is_request'), (b'2', b'accept_friend')], max_length=1),
        ),
    ]
